name: Node ks app deploy to EKS pipeline
on: # Cuando se ejecuta el pipeline
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: # Definicion del pipeline
  deploy:
    runs-on: ubuntu-latest # Servidor donde va a correr (ubuntu, windows, macos)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # uses para builtin functions, run para custom scripts

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR # Container registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: eks-node-app
          IMAGE_TAG: 1.1
        run: |
          docker build -t $REGISTRY/eks-node-app:$IMAGE_TAG .
          docker push $REGISTRY/eks-node-app:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name ada-cluster-2

      - name: Clean up old Pods
        run: |
          kubectl delete pods -l app=eks-node-app

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment eks-node-app

      - name: Check rollout status
        run: |
          kubectl rollout status deployment eks-node-app
